# Admin
sonata_admin:
    title: "AWAZON"
    title_logo: "awazon.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    dashboard:
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 style="margin-top:0">Awazon Backend</h1>
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Providers ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Customers ]

# Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.block.service.text:     ~
        sonata.admin.block.admin_list: ~
