vich_uploader:
    db_driver: orm
    mappings:
        products:
            uri_prefix: "/uploads/image-products"
            upload_destination: "%kernel.project_dir%/public/uploads/image-products"
            namer: Vich\UploaderBundle\Naming\OrignameNamer
