# Put parameters here that don"t need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "ca"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    App\:
        resource: "../src/*"
        exclude: "../src/{Entity,Migrations,Tests,Kernel.php}"
    App\Controller\:
        resource: "../src/Controller"
        tags: ["controller.service_arguments"]
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category, group: Providers }
        public: true
    # Admins
    admin.customer:
        class: App\Admin\CustomerAdmin
        arguments: [~, App\Entity\Customer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Customer, group: Customers }
        public: true

    admin.order:
        class: App\Admin\OrderAdmin
        arguments: [~, App\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Order, group: Customers }
        public: true

    admin.orderitem:
        class: App\Admin\OrderItemAdmin
        arguments: [~, App\Entity\OrderItem, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: OrderItem, group: Customers }
        public: true

    admin.rating:
        class: App\Admin\RatingAdmin
        arguments: [~, App\Entity\Rating, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rating, group: Customers }
        public: true

    admin.review:
        class: App\Admin\ReviewAdmin
        arguments: [~, App\Entity\Review, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Review, group: Customers }
        public: true

    admin.provider:
        class: App\Admin\ProviderAdmin
        arguments: [~, App\Entity\Provider, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Provider, group: Providers }
        public: true

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product, group: Providers }
        public: true

    admin.image:
        class: App\Admin\ImageAdmin
        arguments: [~, App\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image, show_in_dashboard: true, group: Providers }
        public: true
    app.manager.image:
        class: App\Manager\ImageManager
        arguments: ['@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
        public: true
#    app.twig.custom:
#        class: App\Twig\AppCustomTwig
#        arguments: ['@app.manager.image']
#        tags:
#            - { name: twig.extension }
#        public: true
    app.menu_builder:
            class: App\Menu\MenuBuilder
            arguments: ["@knp_menu.factory"]

    app.main_menu:
            class: Knp\Menu\MenuItem # the service definition requires setting the class
            factory: ["@app.menu_builder", createMainMenu]
            arguments: ["@request_stack"]
            tags:
                - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu